---
ID: "f25fe53f-2114-4e33-981d-b2f3469b4374"
Parent: "86549632-95d4-4163-8663-6efa23f4d53d"
Template: "b751a653-89bd-4320-8d5a-2eb82f12a4c1"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/PropertyGridForm/PageSettings/Common/Sections/AdvancedSettings
DB: core
SharedFields:
- ID: "6e242ceb-7aaf-4f4c-b036-9db25d37ec6f"
  Hint: VisualStyle
  Value: ContextPane
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161115T142747Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ee414bab-7885-4c87-b60b-d15255bd8e5b"
      Hint: HeaderText
      Value: Advanced settings
