name: publish to nuget
on:
  push:
    branches:
      - feature/nuget
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: 'latest'
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          working-directory: src/Feature/FormsExtensions/code
      - run: msbuild -t:restore
        working-directory: src/Feature/FormsExtensions/code
      - run: msbuild -t:build
        working-directory: src/Feature/FormsExtensions/code
      - name: Nuget Add Source
        run: nuget sources Add -Name "nugetapi" -Source https://api.nuget.org
      - name: Nuget SetAPIKey
        run: nuget setapikey ${{secrets.NUGET_API_KEY}} -Source "nugetapi"
      - name: Publish the package to GitHub packages
        working-directory: src/Feature/FormsExtensions/code
        run: nuget push bin\Debug\*.nupkg -source "nugetapi" -SkipDuplicate
